services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3307:3306" # usa 3307 en el host para evitar conflictos con un MySQL local
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: usersql
      MYSQL_PASSWORD: usersql
      MYSQL_DATABASE: seg
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build:
      context: ./app-aut
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/seg
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: usersql
    restart: unless-stopped

  frontend:
    build:
      context: ./app-front
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mysql_data:
