version: '3'

services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: usersql
      MYSQL_PASSWORD: usersql
      MYSQL_DATABASE: seg
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    restart: always

  backend:
    build: /back-end/app-aut
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysql:3306/seg?createDatabaseIfNotExist=true&serverTimeZone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: usersql
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

  frontend:
    build: ./front-end/app-front
    ports:
      - "4200:80"
    restart: always
